### ISSUE TITLE
Your website is down

### ISSUE THREAD

**Issue by SamuelMarks** [stacksjs/stacks#1181]
### Describe the bug

https://stacksjs.org/

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/stacksjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/stacksjs/contributing).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrisbbreuer** [comment]
Thanks for reporting. It's an AWS cloud issue I am working on resolving within the coming days, hopefully. In the meantime, I got the landing page up here: https://stacksjs.netlify.app/
